### ISSUE TITLE
Jekyll s2i instructions result in container startup error

### ISSUE THREAD

**Issue by davgordo** [redhat-cop/containers-quickstarts#53]
If I follow the s2i-jekyll readme, I get successful builds for both the base image and the example `openshift-playbooks` app, however, when the application container starts, I see a crashloop with the following log output:

```
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
--
```

**Comment by davgordo** [comment]
I think this may have to do the the security constraint context. I am testing on Minishift.

**Comment by pabrahamsson** [comment]
@davgordo I've submitted PR #62 that should fix the above issue.
The issue you describe is caused by [openshift-playbooks](/redhat-cop/openshift-playbooks) requiring a different ruby version than what is in the Dockerfile for s2i-jekyll. This causes bundler not to install any dependencies from the Gemfile (including jekyll), hence the `bundler: command not found: jekyll` message.

**Comment by davgordo** [comment]
Yes I have verified that upgrading the ruby version fixes this bug. Thanks for fixing.
