### ISSUE TITLE
Fail to pull Kafka image

### ISSUE THREAD

**Issue by mrudul03** [redhat-cop/containers-quickstarts#85]
While following steps to configure Kafka on Openshift, facing an error "Failed to pull image "172.30.1.1:5000/kafka/kafka:latest": rpc error: code = 2 desc = Error: image kafka/kafka:latest not found". 
Zookeeper deployment is also failing with error as "Failed to pull image "172.30.1.1:5000/kafka/zookeeper:3.4.11": rpc error: code = 2 desc = Error: image kafka/zookeeper:3.4.11 not found"

**Comment by pabrahamsson** [comment]
Hi @mrudul03 
What version of OpenShift are you using?
Can you please provide the output of: `oc get imagestream -n kafka`

**Comment by pabrahamsson** [comment]
@mrudul03 can you please provide the above information.
This issue will be closed unless we hear back from you.

**Comment by mrudul03** [comment]
I am using 3.7.1 version. Is this applicable only for OpenShift Enterprise?

**Comment by pabrahamsson** [comment]
We normally only test on OpenShift Container Platform (formerly known as OpenShift Enterprise) but this should also work on Origin.

The messages you are seeing are expected because when the StatefulSets for Zookeeper and Kafka are first created the images do not yet exist in the registry.
Once the images have built successfully (`oc logs bc/zookeeper` and `oc logs bc/zookeeper`) the StatefulSets should pick this up and retry.

**Comment by mrudul03** [comment]
I will try again.

**Comment by mrudul03** [comment]
Below is the output of oc get imagestream -n kafka

NAME        DOCKER REPO                             TAGS                              UPDATED
kafka       172.30.1.1:5000/kafka/kafka                                               
rhel        registry.access.redhat.com/rhel7/rhel   7.4,7.4-164,7.4-152 + 3 more...   4 minutes ago
zookeeper   172.30.1.1:5000/kafka/zookeeper

**Comment by mrudul03** [comment]
I tried again but I am facing the same error.

**Comment by pabrahamsson** [comment]
@mrudul03 the Kafka quickstart has been deprecated by the [Strimzi project](http://strimzi.io/).
